# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flgVpfgEQMIML7yhlVZt87o4Y_D2z0lD
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Dashboard Kualitas Soal", layout="wide")
st.title("📊 Dashboard Analisis Kualitas Soal & Performa Siswa")

# ==============================
# LOAD DATA
# ==============================
df = pd.read_excel("data_simulasi_50_siswa_20_soal.xlsx")

st.success(f"Data: {df.shape[0]} siswa | {df.shape[1]} soal")

# ==============================
# 1️⃣ TOTAL SKOR SISWA
# ==============================
st.header("1️⃣ Distribusi Total Skor Siswa")

df["Total Skor"] = df.sum(axis=1)

fig1, ax1 = plt.subplots()
ax1.hist(df["Total Skor"], bins=8)
ax1.set_xlabel("Total Skor")
ax1.set_ylabel("Jumlah Siswa")
st.pyplot(fig1)

st.write(f"Rata-rata skor total: {df['Total Skor'].mean():.2f}")

# ==============================
# 2️⃣ KLASIFIKASI SISWA
# ==============================
st.header("2️⃣ Klasifikasi Performa Siswa")

mean_total = df["Total Skor"].mean()
std_total = df["Total Skor"].std()

def kategori(x):
    if x >= mean_total + std_total:
        return "Tinggi"
    elif x <= mean_total - std_total:
        return "Rendah"
    else:
        return "Sedang"

df["Kategori"] = df["Total Skor"].apply(kategori)

st.bar_chart(df["Kategori"].value_counts())

# ==============================
# 3️⃣ TINGKAT KESULITAN SOAL
# ==============================
st.header("3️⃣ Analisis Tingkat Kesulitan Soal")

mean_soal = df.iloc[:, :-2].mean()
difficulty = 1 - (mean_soal / df.iloc[:, :-2].max().max())

difficulty_sorted = difficulty.sort_values(ascending=False)

st.subheader("Ranking Soal Tersulit")
st.dataframe(difficulty_sorted.head(5))

fig2, ax2 = plt.subplots(figsize=(10,4))
ax2.bar(difficulty_sorted.index, difficulty_sorted.values)
ax2.set_xticklabels(difficulty_sorted.index, rotation=45)
ax2.set_ylabel("Indeks Kesulitan")
st.pyplot(fig2)

# ==============================
# 4️⃣ DAYA PEMBEDA SEDERHANA
# ==============================
st.header("4️⃣ Analisis Daya Pembeda Soal")

top_group = df[df["Kategori"] == "Tinggi"]
bottom_group = df[df["Kategori"] == "Rendah"]

discrimination = top_group.iloc[:, :-2].mean() - bottom_group.iloc[:, :-2].mean()
discrimination_sorted = discrimination.sort_values(ascending=False)

st.dataframe(discrimination_sorted.head(5))

# ==============================
# 5️⃣ HEATMAP POLA JAWABAN
# ==============================
st.header("5️⃣ Heatmap Pola Jawaban Siswa")

fig3, ax3 = plt.subplots(figsize=(12,6))
sns.heatmap(df.iloc[:, :-2], cmap="YlGnBu", ax=ax3)
st.pyplot(fig3)

# ==============================
# 6️⃣ INSIGHT OTOMATIS
# ==============================
st.header("6️⃣ Insight Otomatis")

soal_tersulit = difficulty_sorted.idxmax()
soal_termudah = difficulty_sorted.idxmin()

st.success(f"""
Soal tersulit: {soal_tersulit}
Soal termudah: {soal_termudah}
Rata-rata total siswa: {df['Total Skor'].mean():.2f}
""")

st.info("Rekomendasi: Evaluasi soal tersulit dan periksa apakah tingkat kesulitannya sesuai dengan indikator pembelajaran.")